In [1]:
import sys
import numpy as np
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
import cmdstanpy

sys.path.append("/Users/dddd1007/project2git/cognitive_control_model/scripts/waskom_bayesian_learner_model")

# import optlearner
import pandas as pd

## 计算 Waskom 的模型

In [2]:
all_sub_data = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/input/all_data_with_2a1d1CCC_2a1d1e.csv")

In [3]:
import optlearner
v_learner = optlearner.VolatilityLearner()
s_learner = optlearner.ProbabilityLearner()

In [6]:
# 计算抽象概念的 AIC 值
AIC_ab_list = []
sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
    env = [1 if x == 'con' else 0 for x in temp_sub['congruency']]
    v_learner.reset()
    v_learner.fit(env)
    y = temp_sub['RT']
    temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
    mini_block = pd.get_dummies(temp_sub[['miniblock']], columns= ['miniblock'])
    mini_block['p_hats'] = v_learner.p_hats
    temp_sub['p_hats'] = v_learner.p_hats
    print(mini_block.values)

    # Save the result
    if (i == 1):
        result_data_frame = temp_sub
    else:
        result_data_frame = pd.concat([result_data_frame, temp_sub])

    model = sm.OLS(y, mini_block.values).fit()
    AIC_ab_list.append(model.aic)
result_data_frame.to_csv("/Users/dddd1007/project2git/cognitive_control_model/data/input/all_data_with_waskom_ab_bl.csv")

/var/folders/b9/72wcckds2cb8251nj_1l8y840000gn/T/ipykernel_77015/984245946.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
/var/folders/b9/72wcckds2cb8251nj_1l8y840000gn/T/ipykernel_77015/984245946.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_sub['p_hats'] = v_learner.p_hats


[[1.         0.         0.         ... 0.         0.         0.34523047]
 [1.         0.         0.         ... 0.         0.         0.51290971]
 [1.         0.         0.         ... 0.         0.         0.6084449 ]
 ...
 [0.         0.         0.         ... 0.         1.         0.21637022]
 [0.         0.         0.         ... 0.         1.         0.31337136]
 [0.         0.         0.         ... 0.         1.         0.28561826]]
[[1.         0.         0.         ... 0.         0.         0.34523047]
 [1.         0.         0.         ... 0.         0.         0.51290971]
 [1.         0.         0.         ... 0.         0.         0.40608315]
 ...
 [0.         0.         0.         ... 0.         1.         0.69867469]
 [0.         0.         0.         ... 0.         1.         0.60629186]
 [0.         0.         0.         ... 0.         1.         0.65022425]]
[[1.         0.         0.         ... 0.         0.         0.65476953]
 [1.         0.         0.         ... 

In [ ]:
AIC_ab_list

[11489.701567044487,
 11452.25365615366,
 11532.682033344341,
 11771.099236518208,
 12613.38020682956,
 11726.722923565814,
 12335.12124419807,
 11737.763952779622,
 12436.835253758725,
 12670.7098200604,
 12902.64231597094,
 12792.658547724808,
 11645.318224035624,
 11960.750731006983,
 12106.937988018475,
 12125.829438619341,
 10523.859270325205,
 12216.492361509621,
 11953.488803682298,
 12686.199658106489,
 12255.583228341187,
 12423.36992458637,
 12341.395506942195,
 10982.461274562884,
 10805.235351862822,
 10801.779507851852,
 11840.167271501989,
 12656.11651805533,
 12036.038035637692,
 11927.09777274356,
 10703.261637618392,
 11098.272024634727,
 12191.731244976396,
 10792.161126517454]

In [ ]:
# 计算抽象概念的 AIC 值
AIC_ab_list_without_volatile = []
sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
    env = [1 if x == 'con' else 0 for x in temp_sub['congruency']]
    s_learner.reset()
    s_learner.fit(env)
    y = temp_sub['RT']
    temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
    mini_block = pd.get_dummies(temp_sub[['miniblock']], columns= ['miniblock'])
    mini_block['p_hats'] = s_learner.p_hats

    model = sm.OLS(y, mini_block.values).fit()
    AIC_ab_list_without_volatile.append(model.aic)

/Users/dddd1007/miniforge3/lib/python3.9/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)


In [ ]:
AIC_ab_list_without_volatile

[11491.271655256085,
 11447.921648122363,
 11532.390693546786,
 11772.228055638701,
 12613.334322797891,
 11725.647140751566,
 12332.715175526104,
 11737.9262575576,
 12436.715422501291,
 12670.684699595438,
 12902.898584704808,
 12796.518844946379,
 11645.795837713515,
 11960.738993471914,
 12107.857701324512,
 12125.861463300294,
 10526.843151225918,
 12216.43738461766,
 11952.929384023302,
 12686.157812687528,
 12256.076373527334,
 12423.442692824254,
 12343.856915178787,
 10982.757658356853,
 10805.919397913505,
 10801.763378313219,
 11840.186601697193,
 12656.066493466593,
 12035.966519406627,
 11927.00715510255,
 10703.447532571512,
 11100.819489926946,
 12191.874173479047,
 10791.991378028852]

In [11]:
# 计算S-R Bayesian Model 的 AIC 值
AIC_sr_list = []
sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]

    # left 
    temp_sub_left = temp_sub[temp_sub['stim_loc'] == 'left']
    env = temp_sub_left['Response']
    v_learner.reset()
    v_learner.fit(env)    
    temp_sub_left['miniblock'] = temp_sub_left["block"].astype(str) + temp_sub_left["run"].astype(str)
    mini_block_left = pd.get_dummies(temp_sub_left[['miniblock', 'Trial']], columns= ['miniblock'])
    mini_block_left['p_hats'] = v_learner.p_hats
    temp_sub_left['p_hats'] = v_learner.p_hats
    temp_sub_left['I_hats'] = v_learner.I_hats

    # right
    temp_sub_right = temp_sub[temp_sub['stim_loc'] == 'right']
    env = temp_sub_right['Response']
    v_learner.reset()
    v_learner.fit(env)
    temp_sub_right['miniblock'] = temp_sub_right["block"].astype(str) + temp_sub_right["run"].astype(str)
    mini_block_right = pd.get_dummies(temp_sub_right[['miniblock', 'Trial']], columns= ['miniblock'])
    mini_block_right['p_hats'] = v_learner.p_hats
    temp_sub_right['p_hats'] = v_learner.p_hats
    temp_sub_right['I_hats'] = v_learner.I_hats

    # Save the result
    if (i == 1):
        result_data_frame = pd.concat([temp_sub_left, temp_sub_right])
    else:
        result_data_frame = pd.concat([result_data_frame, temp_sub_left, temp_sub_right])

    # calculate AIC
    df = pd.concat([temp_sub_left, temp_sub_right]).sort_values(by=['Trial'])
    y = df['RT'].values
    x = pd.concat([mini_block_left, mini_block_right]).sort_values(by=['Trial']).drop('Trial', axis= 1).values
    
    print(x)
    model = sm.OLS(y, x).fit()
    AIC_sr_list.append(model.aic)

result_data_frame.to_csv("/Users/dddd1007/project2git/cognitive_control_model/data/input/all_data_with_waskom_sr_learner.csv")

/var/folders/b9/72wcckds2cb8251nj_1l8y840000gn/T/ipykernel_28545/4035126876.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_sub_left['miniblock'] = temp_sub_left["block"].astype(str) + temp_sub_left["run"].astype(str)
/var/folders/b9/72wcckds2cb8251nj_1l8y840000gn/T/ipykernel_28545/4035126876.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_sub_left['p_hats'] = v_learner.p_hats
/var/folders/b9/72wcckds2cb8251nj_1l8y840000gn/T/ipykernel_28545/4035126876.py:16: SettingWithCopyWarning: 
A va

[[1.         0.         0.         ... 0.         0.         0.34523047]
 [1.         0.         0.         ... 0.         0.         0.34523047]
 [1.         0.         0.         ... 0.         0.         0.27581234]
 ...
 [0.         0.         0.         ... 0.         1.         0.3544496 ]
 [0.         0.         0.         ... 0.         1.         0.65352008]
 [0.         0.         0.         ... 0.         1.         0.69706797]]
[[1.         0.         0.         ... 0.         0.         0.65476953]
 [1.         0.         0.         ... 0.         0.         0.65476953]
 [1.         0.         0.         ... 0.         0.         0.48709029]
 ...
 [0.         0.         0.         ... 0.         1.         0.2717479 ]
 [0.         0.         0.         ... 0.         1.         0.40078062]
 [0.         0.         0.         ... 0.         1.         0.67975243]]
[[1.         0.         0.         ... 0.         0.         0.65476953]
 [1.         0.         0.         ... 

In [ ]:
AIC_sr_list

[11514.140488595363,
 11460.411089099991,
 11524.440887458744,
 11778.027010444393,
 12599.542518739352,
 11715.110655721262,
 12326.457858991354,
 11740.155649014228,
 12439.987629572286,
 12663.334792604284,
 12903.894304673617,
 12819.975721745202,
 11636.219504661105,
 11953.661013136709,
 12107.35295325483,
 12125.198994942915,
 10504.94139707419,
 12215.13323971186,
 11942.661291940836,
 12670.929441250557,
 12246.208401758084,
 12414.498066092263,
 12327.549140061328,
 10982.75745936323,
 10809.084702469507,
 10784.056481286483,
 11835.806357600044,
 12655.213730852109,
 12033.11973453599,
 11925.55324555991,
 10697.610748546595,
 11115.669695907516,
 12191.945317432537,
 10794.428980552473]

In [ ]:
AIC_sr_list_without_k = []
sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]

    # left 
    temp_sub_left = temp_sub[temp_sub['stim_loc'] == 'left']
    env = temp_sub_left['Response']
    s_learner.reset()
    s_learner.fit(env)    
    temp_sub_left['miniblock'] = temp_sub_left["block"].astype(str) + temp_sub_left["run"].astype(str)
    mini_block_left = pd.get_dummies(temp_sub_left[['miniblock', 'Trial']], columns= ['miniblock'])
    mini_block_left['p_hats'] = s_learner.p_hats

    # right
    temp_sub_right = temp_sub[temp_sub['stim_loc'] == 'right']
    env = temp_sub_right['Response']
    s_learner.reset()
    s_learner.fit(env)
    temp_sub_right['miniblock'] = temp_sub_right["block"].astype(str) + temp_sub_right["run"].astype(str)
    mini_block_right = pd.get_dummies(temp_sub_right[['miniblock', 'Trial']], columns= ['miniblock'])
    mini_block_right['p_hats'] = s_learner.p_hats

    # calculate AIC
    df = pd.concat([temp_sub_left, temp_sub_right]).sort_values(by=['Trial'])
    y = df['RT'].values
    x = pd.concat([mini_block_left, mini_block_right]).sort_values(by=['Trial']).drop('Trial', axis= 1).values
    
    model = sm.OLS(y, x).fit()
    AIC_sr_list_without_k.append(model.aic)

In [ ]:
AIC_sr_list_without_k

[11514.09401749766,
 11459.513882311101,
 11525.104181433653,
 11778.018534152365,
 12599.351499634042,
 11717.336740580875,
 12327.049871424777,
 11740.201712011072,
 12439.930341114332,
 12662.470889211558,
 12904.544164836225,
 12820.218836131362,
 11635.807150030272,
 11954.906636081381,
 12106.812073151865,
 12125.173024714091,
 10504.688175261175,
 12215.42144156,
 11942.693174910853,
 12670.808579032666,
 12246.767294442041,
 12414.173829393148,
 12330.896122090406,
 10982.303452923743,
 10809.083037402372,
 10786.324536635568,
 11835.676757503448,
 12655.30769880353,
 12033.471355210306,
 11925.951641042586,
 10697.797073390055,
 11114.49208403343,
 12191.949336554235,
 10794.4402787323]

## 计算 Stan 模型

In [ ]:
ab_learner_stanfile = "/Users/dddd1007/project2git/cognitive_control_model/Bayesian_Models/bayesian_learner_ab.stan"
bayesian_ab_learner = cmdstanpy.CmdStanModel(model_name='bayesian_ab_learner', stan_file=ab_learner_stanfile)

INFO:cmdstanpy:compiling stan program, exe file: /Users/dddd1007/project2git/cognitive_control_model/Bayesian_Models/bayesian_learner_ab
INFO:cmdstanpy:compiler options: stanc_options=None, cpp_options=None
INFO:cmdstanpy:compiled model file: /Users/dddd1007/project2git/cognitive_control_model/Bayesian_Models/bayesian_learner_ab


In [ ]:
AIC_ab_list_stan = []
sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    print('--- Sub ' + str(i) + '---')
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
    env = [1 if x == 'con' else 0 for x in temp_sub['congruency']]
    data = {'N':len(env), 'y':env}
    ab_learner_fit = bayesian_ab_learner.sample(chains=4, data = data)
    result = ab_learner_fit.summary()
    p_hats = result.Mean.values[result.Mean.index.str.contains('r')]
    temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
    mini_block = pd.get_dummies(temp_sub[['miniblock']], columns= ['miniblock'])
    mini_block['p_hats'] = p_hats
    rts = temp_sub['RT'].values

    model = sm.OLS(rts, mini_block.values).fit()
    AIC_ab_list_stan.append(model.aic)

In [ ]:
AIC_ab_list_stan

[11498.160639852422,
 11468.070301899448,
 11534.545431761677,
 11770.592653455447,
 12615.237533096524,
 11728.072605044075,
 12339.84208342117,
 11739.526738962264,
 12440.1207934304,
 12670.525756605053,
 12904.063096265276,
 12811.038041170914,
 11646.75404984532,
 11957.329444890323,
 12106.094855146117,
 12125.862620932307,
 10531.051989267684,
 12216.037226075036,
 11954.397742098477,
 12685.606523833068,
 12256.753535531236,
 12417.37070376609,
 12345.65829740235,
 10989.711180971613,
 10809.117257745984,
 10801.41540460582,
 11839.22328751961,
 12654.637441839177,
 12035.988835341734,
 11927.11851191838,
 10702.036321467243,
 11109.225693927272,
 12188.5916050771,
 10790.360793308444]

In [ ]:
sr_learner_stanfile = "/Users/dddd1007/project2git/cognitive_control_model/Bayesian_Models/bayesian_learner_sr.stan"
bayesian_sr_learner = cmdstanpy.CmdStanModel(model_name='bayesian_sr_learner', stan_file=sr_learner_stanfile)

INFO:cmdstanpy:compiling stan program, exe file: /Users/dddd1007/project2git/cognitive_control_model/Bayesian_Models/bayesian_learner_sr
INFO:cmdstanpy:compiler options: stanc_options=None, cpp_options=None
INFO:cmdstanpy:compiled model file: /Users/dddd1007/project2git/cognitive_control_model/Bayesian_Models/bayesian_learner_sr


In [ ]:
sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    print('--- Sub ' + str(i) + '---')
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
    react = temp_sub['Response'].values
    space_loc = [1 if x == 'right' else 0 for x in temp_sub['stim_loc']]
    data = {'N':len(react), 'react':react, 'space_loc':space_loc}
    process_file_loc = '/Users/dddd1007/project2git/cognitive_control_model/data/output/bayesian_learner_samplers/sr/process/sub' + str(i) + '/.'
    sr_learner_fit = bayesian_sr_learner.sample(chains=4, data = data,
                                                output_dir=process_file_loc,
                                                show_progress=True)
    result = sr_learner_fit.summary()
    file_name = 'sub_' + str(i) + '_sr_learner.csv'
    result.to_csv('/Users/dddd1007/project2git/cognitive_control_model/data/output/bayesian_learner_samplers/sr_learner/' + file_name)

--- Sub 1---


Chain 1 - warmup:   0%|          | 0/1 [00:00<?, ?it/s]





Chain 1 - warmup:   0%|          | 0/2000 [00:00<?, ?it/s]




In [ ]:
AIC_sr_list_stan = []
sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    print('--- Sub ' + str(i) + '---')
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
    estimated_data = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/output/bayesian_learner_samplers/sr/extracted_data/sub_" + str(i) + "_sr_learner_.csv")
    p_hats = estimated_data['r_selected']
    temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
    mini_block = pd.get_dummies(temp_sub[['miniblock']], columns= ['miniblock'])
    mini_block['p_hats'] = p_hats
    rts = temp_sub['RT'].values

    model = sm.OLS(rts, mini_block.values).fit()
    AIC_sr_list_stan.append(model.aic)

--- Sub 20---


In [ ]:
AIC_sr_list_stan

[11955.201928882132]

## 比较 stan 下 1k1v, 1k1v, 2k2v

In [ ]:
# 1k1v
all_sub_data = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/input/all_data_with_sr_bayesian_learner_scaled.csv")
AIC_1k1v_list_stan = []
MSE_1k1v_list_stan = []
sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    print('--- Sub ' + str(i) + '---')
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
    estimated_data = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/output/bayesian_learner_samplers/compare_1k1v_1k2v_2k2v/1k1v/extracted_data/sub_" + str(i) + "_sr_learner.csv")
    p_hats = estimated_data['r_selected']
    temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
    mini_block = pd.get_dummies(temp_sub[['miniblock']], columns= ['miniblock'])
    mini_block.loc[:,'p_hats'] = p_hats.values
    rts = temp_sub['RT'].values

    model = sm.OLS(rts, mini_block.values).fit()
    AIC_1k1v_list_stan.append(model.aic)
    MSE_1k1v_list_stan.append(model.mse_resid)

--- Sub 1---
--- Sub 2---
--- Sub 3---
--- Sub 4---
--- Sub 5---
--- Sub 7---
--- Sub 8---
--- Sub 9---
--- Sub 10---
--- Sub 11---
--- Sub 12---
--- Sub 13---
--- Sub 14---
--- Sub 15---


/var/folders/b9/72wcckds2cb8251nj_1l8y840000gn/T/ipykernel_55045/4233430404.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)


--- Sub 17---
--- Sub 18---
--- Sub 19---
--- Sub 21---
--- Sub 22---
--- Sub 23---
--- Sub 24---
--- Sub 25---
--- Sub 26---
--- Sub 28---
--- Sub 29---
--- Sub 30---
--- Sub 31---
--- Sub 32---
--- Sub 33---
--- Sub 34---
--- Sub 35---
--- Sub 36---


In [ ]:
MSE_1k1v_list_stan

[8831.458801188091,
 8580.770536750873,
 32032.867266374047,
 12596.55950238348,
 31390.920399299783,
 11117.913556134223,
 27571.85854343381,
 11649.82200607411,
 26211.364897979605,
 32209.130070950792,
 39812.52936959231,
 37893.84371867824,
 11018.049539310887,
 15351.555705902301,
 17219.97264960709,
 3273.5932404514283,
 39250.74345982228,
 37571.362713728326,
 37342.5005372043,
 23768.751157687428,
 20867.446478493264,
 5318.200828619694,
 18636.274653673005,
 4526.9554805780635,
 12947.959588025085,
 32352.75582624329,
 15628.705275608245,
 15543.553151974189,
 30299.070444625322,
 5807.971874641829,
 31700.71255043335,
 4165.227995159207]

In [ ]:
# 1k2v
AIC_1k2v_list_stan = []
sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    print('--- Sub ' + str(i) + '---')
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
    estimated_data = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/output/bayesian_learner_samplers/compare_1k1v_1k2v_2k2v/1k2v/extracted_data/sub_" + str(i) + "_sr_learner.csv")
    p_hats = estimated_data['r_selected']
    temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
    mini_block = pd.get_dummies(temp_sub[['miniblock']], columns= ['miniblock'])
    mini_block.loc[:,'p_hats'] = p_hats.values
    rts = temp_sub['RT'].values

    model = sm.OLS(rts, mini_block.values).fit()
    AIC_1k2v_list_stan.append(model.aic)

--- Sub 1---
--- Sub 2---
--- Sub 3---
--- Sub 4---
--- Sub 5---
--- Sub 7---
--- Sub 8---
--- Sub 9---
--- Sub 10---
--- Sub 11---
--- Sub 12---
--- Sub 13---
--- Sub 14---
--- Sub 15---
--- Sub 17---
--- Sub 18---
--- Sub 19---
--- Sub 21---
--- Sub 22---
--- Sub 23---
--- Sub 24---
--- Sub 25---


/var/folders/b9/72wcckds2cb8251nj_1l8y840000gn/T/ipykernel_26069/4100950327.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)


--- Sub 26---
--- Sub 28---
--- Sub 29---
--- Sub 30---
--- Sub 31---
--- Sub 32---
--- Sub 33---
--- Sub 34---
--- Sub 35---
--- Sub 36---


In [ ]:
AIC_1k2v_list_stan

[11470.623163612794,
 11444.460771098458,
 11532.721677840436,
 11763.244922589474,
 12609.658040490734,
 11693.004720191922,
 12329.810186751585,
 11737.059001469335,
 12438.04830150338,
 12645.974177995135,
 12876.60070891965,
 12816.431667044084,
 11635.300138494396,
 11952.862645708326,
 12111.635672859726,
 10518.003719523876,
 12209.906040088425,
 12674.014633446484,
 12227.63841670893,
 12422.030039724621,
 12298.69001269934,
 10984.75060885176,
 10807.066680591535,
 10796.323653363232,
 11838.932111020667,
 12639.872232945787,
 12019.000747892218,
 11888.711124513902,
 10695.052536593721,
 11069.672417451377,
 12184.027542606887,
 10749.63060664191]

In [ ]:
# 2k2v
AIC_2k2v_list_stan = []
sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    print('--- Sub ' + str(i) + '---')
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
    estimated_data = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/output/bayesian_learner_samplers/compare_1k1v_1k2v_2k2v/2k2v/extracted_data/sub_" + str(i) + "_sr_learner.csv")
    p_hats = estimated_data['r_selected']
    temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
    mini_block = pd.get_dummies(temp_sub[['miniblock']], columns= ['miniblock'])
    mini_block.loc[:,'p_hats'] = p_hats.values
    rts = temp_sub['RT'].values

    model = sm.OLS(rts, mini_block.values).fit()
    AIC_2k2v_list_stan.append(model.aic)
AIC_2k2v_list_stan

--- Sub 1---
--- Sub 2---
--- Sub 3---
--- Sub 4---
--- Sub 5---
--- Sub 7---
--- Sub 8---
--- Sub 9---
--- Sub 10---
--- Sub 11---
--- Sub 12---
--- Sub 13---
--- Sub 14---
--- Sub 15---
--- Sub 17---
--- Sub 18---
--- Sub 19---
--- Sub 21---
--- Sub 22---
--- Sub 23---
--- Sub 24---
--- Sub 25---
--- Sub 26---
--- Sub 28---


/var/folders/b9/72wcckds2cb8251nj_1l8y840000gn/T/ipykernel_26069/3706457389.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)


--- Sub 29---
--- Sub 30---
--- Sub 31---
--- Sub 32---
--- Sub 33---
--- Sub 34---
--- Sub 35---
--- Sub 36---


[11473.31670689139,
 11443.99560454652,
 11532.430121295847,
 11763.674411764609,
 12609.571069242702,
 11693.243858369742,
 12330.004287495387,
 11737.963113853308,
 12438.133778136751,
 12646.612908549127,
 12877.43143236054,
 12816.714740664227,
 11636.131733188853,
 11952.953782805027,
 12111.982611555102,
 10518.066387640965,
 12207.398483046685,
 12674.254030598251,
 12227.45441577886,
 12422.067626075976,
 12297.498126335666,
 10984.125096637883,
 10807.096366302729,
 10796.46732222751,
 11838.93694132159,
 12638.543696835313,
 12020.429237379873,
 11887.326919261111,
 10694.714522416998,
 11069.313231788214,
 12183.960655228593,
 10749.073165152526]

In [ ]:
AIC_2k2v_list_stan

[11473.31670689139,
 11443.99560454652,
 11532.430121295847,
 11763.674411764609,
 12609.571069242702,
 11693.243858369742,
 12330.004287495387,
 11737.963113853308,
 12438.133778136751,
 12646.612908549127,
 12877.43143236054,
 12816.714740664227,
 11636.131733188853,
 11952.953782805027,
 12111.982611555102,
 10518.066387640965,
 12207.398483046685,
 12674.254030598251,
 12227.45441577886,
 12422.067626075976,
 12297.498126335666,
 10984.125096637883,
 10807.096366302729,
 10796.46732222751,
 11838.93694132159,
 12638.543696835313,
 12020.429237379873,
 11887.326919261111,
 10694.714522416998,
 11069.313231788214,
 12183.960655228593,
 10749.073165152526]

In [ ]:
# ab 校正了拟合的 p 的对象
AIC_ab_list_stan = []
MSE_ab_list_stan = []
sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    print('--- Sub ' + str(i) + '---')
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
    estimated_data = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/output/bayesian_learner_samplers/ab/process/extracted_data/sub_" + str(i) + "_ab_learner.csv")
    p_hats = estimated_data['r_selected']
    temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
    mini_block = pd.get_dummies(temp_sub[['miniblock']], columns= ['miniblock'])
    mini_block.loc[:,'p_hats'] = p_hats.values
    rts = temp_sub['RT'].values

    model = sm.OLS(rts, mini_block.values).fit()
    AIC_ab_list_stan.append(model.aic)
    MSE_ab_list_stan.append(model.mse_resid)

--- Sub 1---
--- Sub 2---
--- Sub 3---
--- Sub 4---
--- Sub 5---
--- Sub 7---
--- Sub 8---
--- Sub 9---
--- Sub 10---
--- Sub 11---
--- Sub 12---
--- Sub 13---
--- Sub 14---
--- Sub 15---
--- Sub 17---
--- Sub 18---
--- Sub 19---
--- Sub 21---
--- Sub 22---
--- Sub 23---
--- Sub 24---


/var/folders/b9/72wcckds2cb8251nj_1l8y840000gn/T/ipykernel_26069/465745241.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)


--- Sub 25---
--- Sub 26---
--- Sub 28---
--- Sub 29---
--- Sub 30---
--- Sub 31---
--- Sub 32---
--- Sub 33---
--- Sub 34---
--- Sub 35---
--- Sub 36---


In [ ]:
# ab 校正了拟合的 p 的对象
AIC_ab_list_stan = []
MSE_ab_list_stan = []
BIC_ab_list_stan = []
sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    print('--- Sub ' + str(i) + '---')
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
    estimated_data = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/output/bayesian_learner_samplers/ab/process/extracted_data/sub_" + str(i) + "_ab_learner.csv")
    p_hats = estimated_data['r_selected']
    temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
    mini_block = pd.get_dummies(temp_sub[['miniblock']], columns= ['miniblock'])
    mini_block.loc[:,'p_hats'] = p_hats.values
    rts = temp_sub['RT'].values

    model = sm.OLS(rts, mini_block.values).fit()
    AIC_ab_list_stan.append(model.aic)
    MSE_ab_list_stan.append(model.mse_resid)
    BIC_ab_list_stan.append(model.bic)

--- Sub 1---
--- Sub 2---
--- Sub 3---
--- Sub 4---
--- Sub 5---
--- Sub 7---
--- Sub 8---
--- Sub 9---
--- Sub 10---
--- Sub 11---
--- Sub 12---
--- Sub 13---
--- Sub 14---
--- Sub 15---
--- Sub 17---
--- Sub 18---
--- Sub 19---
--- Sub 21---
--- Sub 22---
--- Sub 23---
--- Sub 24---
--- Sub 25---
--- Sub 26---
--- Sub 28---
--- Sub 29---
--- Sub 30---
--- Sub 31---
--- Sub 32---
--- Sub 33---


/var/folders/b9/72wcckds2cb8251nj_1l8y840000gn/T/ipykernel_13515/3183485837.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)


--- Sub 34---
--- Sub 35---
--- Sub 36---


In [ ]:
BIC_ab_list_stan

[11590.277101247553,
 11569.161839935654,
 11651.25871465985,
 11890.867157217792,
 12730.277105441824,
 11821.323260021738,
 12441.531051735465,
 11856.845936299753,
 12557.836445813007,
 12768.617453553896,
 12999.73231219099,
 12937.84814776008,
 11759.19670105546,
 12078.777015716649,
 12232.407215061929,
 10638.57742190494,
 12317.47670660908,
 12797.13873567516,
 12357.75888870599,
 12545.575272603079,
 12435.259421428404,
 11103.901113866748,
 10925.023937139658,
 10916.7415382504,
 11961.042945364647,
 12761.546142804169,
 12141.597175895406,
 12012.235439163358,
 10812.913003699847,
 11201.521932360243,
 12301.684476176286,
 10875.537306345124]

In [ ]:
# 1k1v wihtout mini block
all_sub_data = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/input/all_data_with_sr_bayesian_learner_scaled.csv")
AIC_1k1v_list_stan = []
MSE_1k1v_list_stan = []
BIC_1k1v_list_stan = []

sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    print('--- Sub ' + str(i) + '---')
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
    estimated_data = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/output/bayesian_learner_samplers/compare_1k1v_1k2v_2k2v/1k1v/extracted_data/sub_" + str(i) + "_sr_learner.csv")
    p_hats = estimated_data['r_selected']
    temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
    mini_block = pd.get_dummies(temp_sub[['miniblock']], columns= ['miniblock'])
    mini_block.loc[:,'p_hats'] = p_hats.values
    rts = temp_sub['RT'].values

    model = sm.OLS(rts, mini_block.values).fit()
    AIC_1k1v_list_stan.append(model.aic)
    MSE_1k1v_list_stan.append(model.mse_resid)
    BIC_1k1v_list_stan.append(model.bic)

--- Sub 1---
--- Sub 2---
--- Sub 3---
--- Sub 4---
--- Sub 5---
--- Sub 7---
--- Sub 8---
--- Sub 9---
--- Sub 10---
--- Sub 11---
--- Sub 12---
--- Sub 13---
--- Sub 14---
--- Sub 15---
--- Sub 17---
--- Sub 18---
--- Sub 19---
--- Sub 21---
--- Sub 22---
--- Sub 23---
--- Sub 24---
--- Sub 25---
--- Sub 26---
--- Sub 28---
--- Sub 29---
--- Sub 30---
--- Sub 31---
--- Sub 32---
--- Sub 33---


/var/folders/b9/72wcckds2cb8251nj_1l8y840000gn/T/ipykernel_13515/1917487246.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)


--- Sub 34---
--- Sub 35---
--- Sub 36---


In [ ]:
# ab 校正了拟合的 p 的对象
AIC_ab_list_stan = []
MSE_ab_list_stan = []
sub_list = np.unique(all_sub_data['Subject_num'].values)
i = 1    
print('--- Sub ' + str(i) + '---')
temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
estimated_data = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/output/bayesian_learner_samplers/ab/process/extracted_data/sub_" + str(i) + "_ab_learner.csv")
p_hats = estimated_data['r_selected']
temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
mini_block = pd.get_dummies(temp_sub[['miniblock']], columns= ['miniblock'])
mini_block.loc[:,'p_hats'] = p_hats.values
rts = temp_sub['RT'].values

model = sm.OLS(rts, mini_block.values).fit()
model.summary()

--- Sub 1---


/var/folders/b9/72wcckds2cb8251nj_1l8y840000gn/T/ipykernel_13515/3517340059.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.104
Model:                            OLS   Adj. R-squared:                  0.081
Method:                 Least Squares   F-statistic:                     4.519
Date:                Wed, 13 Oct 2021   Prob (F-statistic):           6.68e-12
Time:                        16:14:42   Log-Likelihood:                -5709.3
No. Observations:                 960   AIC:                         1.147e+04
Df Residuals:                     935   BIC:                         1.159e+04
Df Model:                          24                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           501.9484     18.462     27.189      0.000     465.717     538.180
x2           559.0049     18.106     30.874      0.000     523.472     594.538
x3           499.7989     18.378     27.195      0.000     463.731     535.866
x4           511.7925     18.222     28.087      0.000     476.032     547.553
x5           514.9916     18.309     28.128      0.000     479.061     550.923
x6           490.7508     18.182     26.991      0.000     455.069     526.433
x7           560.9323     17.932     31.281      0.000     525.740     596.124
x8           528.7934     18.184     29.080      0.000     493.107     564.480
x9           564.1494     17.821     31.657      0.000     529.176     599.123
x10          515.2444     18.439     27.943      0.000     479.057     551.431
x11          523.6683     18.044     29.021      0.000     488.256     559.080
x12          552.1375     18.165     30.395      0.000     516.488     587.787
x13          555.5226     18.185     30.548      0.000     519.834     591.211
x14          526.5450     17.931     29.365      0.000     491.355     561.735
x15          490.0507     17.699     27.689      0.000     455.317     524.784
x16          498.3250     18.371     27.125      0.000     462.271     534.379
x17          522.3472     18.189     28.718      0.000     486.652     558.043
x18          522.5731     18.472     28.289      0.000     486.321     558.825
x19          559.4204     18.370     30.453      0.000     523.369     595.471
x20          548.9218     18.578     29.547      0.000     512.462     585.381
x21          502.4182     18.151     27.680      0.000     466.796     538.040
x22          518.9255     18.150     28.590      0.000     483.305     554.546
x23          517.1974     18.518     27.930      0.000     480.856     553.539
x24          551.2508     18.442     29.890      0.000     515.057     587.444
x25         -109.5289     16.147     -6.783      0.000    -141.217     -77.840
==============================================================================
Omnibus:                      412.896   Durbin-Watson:                   1.858
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2241.185
Skew:                           1.922   Prob(JB):                         0.00
Kurtosis:                       9.423   Cond. No.                         13.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
import scipy
corr_list = []
for i in sub_list:
    print('--- Sub ' + str(i) + '---')
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
    estimated_data_ab = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/output/bayesian_learner_samplers/ab/process/extracted_data/sub_" + str(i) + "_ab_learner.csv")
    estimated_data_sr = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/output/bayesian_learner_samplers/compare_1k1v_1k2v_2k2v/1k1v/extracted_data/sub_" + str(i) + "_sr_learner.csv")
    ab_v = estimated_data_ab['v']
    sr_v = estimated_data_sr['v']
    corr_coef = scipy.stats.pearsonr(ab_v, sr_v)
    corr_list.append(corr_coef[0])

--- Sub 1---
--- Sub 2---
--- Sub 3---
--- Sub 4---
--- Sub 5---
--- Sub 7---
--- Sub 8---
--- Sub 9---
--- Sub 10---
--- Sub 11---
--- Sub 12---
--- Sub 13---
--- Sub 14---
--- Sub 15---
--- Sub 17---
--- Sub 18---
--- Sub 19---
--- Sub 21---
--- Sub 22---


ValueError: array must not contain infs or NaNs

In [5]:

all_sub_data = pd.read_csv("/Users/dddd1007/project2git/cognitive_control_model/data/input/all_data_with_rl_model.csv")
AIC_rl_model = []

sub_list = np.unique(all_sub_data['Subject_num'].values)
for i in sub_list:
    print('--- Sub ' + str(i) + '---')
    temp_sub = all_sub_data[all_sub_data['Subject_num'] == i]
    p_hats = temp_sub['p']
    temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
    mini_block = pd.get_dummies(temp_sub[['miniblock']], columns= ['miniblock'])
    mini_block.loc[:,'p_hats'] = p_hats.values
    rts = temp_sub['RT'].values

    model = sm.OLS(rts, mini_block.values).fit()
    AIC_rl_model.append(model.aic)

--- Sub 1---
--- Sub 2---
--- Sub 3---
--- Sub 4---
--- Sub 5---
--- Sub 7---
--- Sub 8---
--- Sub 9---
--- Sub 10---
--- Sub 11---
--- Sub 12---
--- Sub 13---
--- Sub 14---
--- Sub 15---
--- Sub 16---
--- Sub 17---
--- Sub 18---
--- Sub 19---
--- Sub 20---
--- Sub 21---
--- Sub 22---
--- Sub 23---
--- Sub 24---
--- Sub 25---
--- Sub 26---
--- Sub 28---
--- Sub 29---
--- Sub 30---
--- Sub 31---
--- Sub 32---
--- Sub 33---
--- Sub 34---
--- Sub 35---
--- Sub 36---


/var/folders/b9/72wcckds2cb8251nj_1l8y840000gn/T/ipykernel_40074/820045846.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_sub['miniblock'] = temp_sub["block"].astype(str) + temp_sub["run"].astype(str)
